plugins:
  - uses:  
    - plugin: ubiquity-whilefoo/daemon-pricing@fix/label-generation
      with:
        globalConfigUpdate:
          excludeRepos: []
        basePriceMultiplier: 2
        labels:
         time:
           - name: "Time: <1 Hour"
           - name: "Time: <2 Hours"
           - name: "Time: <4 Hours"
           - name: "Time: <1 Day"
           - name: "Time: <1 Week"
         priority:
           - name: "Priority: 1 (Normal)"
           - name: "Priority: 2 (Medium)"
           - name: "Priority: 3 (High)"
           - name: "Priority: 4 (Urgent)"
           - name: "Priority: 5 (Emergency)"
